export * from './Header'
export * from './Footer'
export * from './MenuCliente'
export * from './Bienvenida'
export * from './AgregarDenuncia'
export * from './CategoriaDenuncia'
export * from './Denuncia'
export * from './VerCategorias'
